### ISSUE TITLE
Add config file for defining vms

### ISSUE THREAD

**Issue by ALSchwalm** [mythril-hypervisor/mythril#40]
## Summary

We need to take a config file as a multiboot module and retrieve the vm definitions from it. I don't have a strong preference for how this is structured at the moment, but something like:

```
{
  "version": 1,
  "vms": [
    {
      "memory": 128,
      "cpus": [1],
      "kernel": "some_kernel",
      "initramfs": "some_initramfs",
      "cmdline": "foo=bar baz=10"
    },
    {
      "memory": 128,
      "cpus": [2],
      "kernel": "some_other_kernel",
      "initramfs": "some_other_initramfs",
      "cmdline": "foo=bar baz=10"
    }
  ]
}
```

This file should be consumed in `main` rather than the hard coded vms we use right now.

## Relevant files

[mythril_multiboot2/src/main.rs]

[mythril_multiboot2/src/main.rs]: https://github.com/mythril-hypervisor/mythril/blob/master/mythril_multiboot2/src/main.rs#L29

**Comment by sruffell** [comment]
I'll try my hand at this. Looks like one that should allow me to focus on Rust primarily.

**Comment by sruffell** [comment]
I have my WIP on https://github.com/sruffell/mythril/commits/config-file-for-vms.

It's currently parsing the config from the multiboot header, but I'm currently only looking at the first virtual machine in the vms array, and using that in the default_vm function.  I believe I still need to use the number of vms defined in the config to control how many vms are instantiated.

**Comment by ALSchwalm** [comment]
This has been done
