### ISSUE TITLE
acpi: parse the FADT system description table

### ISSUE THREAD

**Issue by dlrobertson** [mythril-hypervisor/mythril#52]
## Summary

Parse and build a structure with the info in the FADT found in the RSDT. See section 5.2.9 in [ACPI] and the relevant OSDev wiki page [FADT].

[ACPI]: https://uefi.org/sites/default/files/resources/ACPI_6_3_final_Jan30.pdf
[FADT]: https://wiki.osdev.org/FADT

**Comment by ntegan** [comment]
I could start looking at this

**Comment by barkera** [comment]
I'll tackle this.
