### ISSUE TITLE
acpi: parse the HPET system description table

### ISSUE THREAD

**Issue by dlrobertson** [mythril-hypervisor/mythril#53]
## Summary

Parse and build a structure with the info in the HPET found in the RSDT. See section 3.2.4 in [HPET spec] and the relevant OSDev wiki page [HPET].

[HPET spec]: https://www.intel.com/content/dam/www/public/us/en/documents/technical-specifications/software-developers-hpet-spec-1-0a.pdf
[HPET]: https://wiki.osdev.org/HPET

**Comment by barkera** [comment]
I can take this issue.

**Comment by ALSchwalm** [comment]
Awesome. This will be really handy for distributing time interrupts to the guests.
