### ISSUE TITLE
acpi: add support for the XSDT

### ISSUE THREAD

**Issue by dlrobertson** [mythril-hypervisor/mythril#54]
# Summary

We currently only support the 32-bit RSDT, but should also support the 64-bit XSDT.

# Details

We do not return the RSDT if the RSDP version corresponds to ACPI 2.0.

https://github.com/mythril-hypervisor/mythril/blob/master/mythril_core/src/acpi/rsdp.rs#L203

There are several locations where we assume the pointer size to be 32 bits

https://github.com/mythril-hypervisor/mythril/blob/master/mythril_core/src/acpi/rsdt.rs#L167

**Comment by ntegan** [comment]
yes

**Comment by ntegan** [comment]
Works more or less

https://github.com/ntegan/mythril/tree/54-xsdt
