### ISSUE TITLE
core: switch to num_enum for TryFromPrimitive

### ISSUE THREAD

**Issue by dlrobertson** [mythril-hypervisor/mythril#64]
# Summary

Switch to [num_enum] for the `TryFromPrimitive` implementation so that we can make dealing with `try_from` errors more ergonomic.

# Details

[derive-try-from-primitive] does not make the returned error type public. This makes dealing with an error from `try_from` cumbersome to deal with. The [num_enum] crate does make the returned error type of `try_from` public. We should implement the following in `mythril_core/src/error.rs`:

```rust
impl<T: TryFromPrimitive> From<TryFromPrimitiveError<T>> for Error {
    // ...
}
```

And then switch all uses of `derive_try_from_primitive` to `num_enum`.

[derive-try-from-primitive]: https://crates.io/crates/derive-try-from-primitive
[num_enum]: https://crates.io/crates/num_enum

**Comment by ntegan** [comment]
yeet
