### ISSUE TITLE
Add interrupt  range method to IoApic

### ISSUE THREAD

**Issue by dlrobertson** [mythril-hypervisor/mythril#88]
Add a convenience function to the [IoApic] implementation that returns a [Range] of the interrupt vectors that should be associated with the [IoApic]. The implementation should return a range from `ioapic.gsi_base` to `ioapic.gsi_base + ioapic.max_redirection_entry()`

The convenience function can then be use in [ioapic_for_gsi]  to simplify the logic there. For example the condition could be changed to use [Range::contains]

[IoApic]: https://github.com/mythril-hypervisor/mythril/blob/master/mythril/src/ioapic.rs#L109
[Range]: https://doc.rust-lang.org/beta/core/ops/struct.Range.html
[Range::contains]: https://doc.rust-lang.org/beta/core/ops/struct.Range.html#method.contains
[ioapic_for_gsi]: https://github.com/mythril-hypervisor/mythril/blob/master/mythril/src/ioapic.rs#L109

**Comment by nolandda** [comment]
I'll try to tackle this.

**Comment by ALSchwalm** [comment]
Thanks!

**Comment by dlrobertson** [comment]
Awesome! Thanks @nolandda

**Comment by nolandda** [comment]
Should be closed by https://github.com/mythril-hypervisor/mythril/pull/92

**Comment by dlrobertson** [comment]
Yup! Thanks!
